version: '3.8'

networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - './certificates:/etc/nginx/certificates'
    depends_on:
      - backend
      - frontend
    networks:
      - dev

  backend:
    build:
      context: ./tapnplay-mini-app-backend
    networks:
      - dev

  frontend:
    build:
      context: ./tapnplay-mini-app
    networks:
      - dev
